name: docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.x
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 2.2.0
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Disable poetry venv
        run: poetry config virtualenvs.create false
      - name: Install deps
        run: poetry install --only=docs
      - run: mkdocs gh-deploy --force
